apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spring-server-virtualservice
spec:
  hosts:
  - spring-server
  http:
  - name: "v1-routes"
    match:
    - headers:
        version:
          exact: v1
      uri:
        exact: /router
      ignoreUriCase: false
    route:
    - destination:
        host: spring-server
        subset: v1
        port:
          number: 8081
  - name: "v2-routes"
    match:
      - headers:
          version:
            exact: v2
        uri:
          prefix: /
        ignoreUriCase: false
    route:
      - destination:
          host: spring-server
          port:
            number: 8081
  - name: "base-route"
    match:
      - headers:
          version:
            exact: base
        uri:
          prefix: /
        ignoreUriCase: false
    route:
    - destination:
        host: spring-server
        subset: v1
        port:
          number: 8081
      weight: 0
    - destination:
        host: spring-server
        subset: v2
        port:
          number: 8081
      weight: 100