apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-client
  template:
    metadata:
      labels:
        app: spring-client
    spec:
      containers:
      - name: spring-client
        image: spring-client:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: token-volume
          mountPath: /var/run/secrets/tokens
          readOnly: true
        env:
        - name: agent_service_dynamic_config_enable
          value: "false"
        - name: agent_service_xds_service_enable
          value: "true"
        - name: agent_config_ignoredPrefixes
          value: "com.huaweicloud.sermant"
        - name: xds_service_discovery_upstreamServiceName
          value: "spring-server"
        - name: xds_service_discovery_type
          value: "subscribe"
        - name: xds_config_control_plane_address
          value: "istiod.istio-system.svc:15012"
        - name: xds_config_security_enable
          value: "true"
        - name: xds_config_service_account_token_path
          value: "/var/run/secrets/tokens/token"
      volumes:
      - name: token-volume
        secret:
          secretName: istio-test-secret
      imagePullSecrets:
        - name: default-secret
---
apiVersion: v1
kind: Service
metadata:
  name: spring-client
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-client