# Spring Boot应用程序配置
spring:
  application:
    name: alibaba-dubbo-consumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 9041

# Dubbo配置
dubbo:
  application:
    name: alibaba-dubbo-consumer
    qos-port: 33335
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: -1