name: "MQ Consume Prohibition Plugin rocketmq Test"
description: "Auto test for mq consume prohibition by rocketmq with one topic"
runs:
  using: composite
  steps:
    - name: entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/mq-consume-prohibition/rocketmq-one-topic
    - name: start mysql
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        systemctl status mysql.service
#    - name: Set up root password
#      shell: bash
#      run: |
#        TEMP_PASSWORD=$(sudo grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}')
#        mysql -u root -p"$TEMP_PASSWORD" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
#        mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
    - name: exit
      if: always()
      uses: ./.github/actions/common/exit
      with:
        processor-keyword: rocketmq
    - name: if failure then upload error log
      uses: actions/upload-artifact@v3
      if: ${{ failure() || cancelled() }}
      with:
        name: (${{ github.job }})-mq-consume-prohibition-rocketmq-one-topic-(${{ matrix.rocketMqVersion }}-logs
        path: |
          ./*.log
          ./logs/**
        if-no-files-found: warn
        retention-days: 2