name: "MQ Consume Prohibition Plugin rocketmq Test"
description: "Auto test for mq consume prohibition by rocketmq with one topic"
runs:
  using: composite
  steps:
    - name: entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/mq-consume-prohibition/rocketmq-one-topic
    - name: start mysql
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo sed -i '/^\[mysqld\]/a skip-grant-tables' /etc/mysql/mysql.conf.d/mysqld.cnf
        sudo systemctl start mysql.service
        sudo systemctl status mysql.service
        sudo mysql -u root -p
    - name: start mongodb
      shell: bash
      run: |
        sudo apt-get install gnupg curl
        curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
           sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
           --dearmor
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org
        sudo systemctl start mongod
        sudo systemctl status mongod
#    - name: Set up root password
#      shell: bash
#      run: |
#        TEMP_PASSWORD=$(sudo grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}')
#        mysql -u root -p"$TEMP_PASSWORD" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
#        mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
#    - name: exit
#      if: always()
#      uses: ./.github/actions/common/exit
#      with:
#        processor-keyword: rocketmq
#    - name: if failure then upload error log
#      uses: actions/upload-artifact@v3
#      if: ${{ failure() || cancelled() }}
#      with:
#        name: (${{ github.job }})-mq-consume-prohibition-rocketmq-one-topic-(${{ matrix.rocketMqVersion }}-logs
#        path: |
#          ./*.log
#          ./logs/**
#        if-no-files-found: warn
#        retention-days: 2