name: "Database Write Prohibition Plugin MySQL Test"
description: "Auto test for mysql write prohibition"
runs:
  using: composite
  steps:
    - name: entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/databse-write-prohibition/mysql
    - name: start mysql
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo sed -i '/^\s*#\s*\(pid-file\|socket\|port\|datadir\)/ s/^#\s*//' /etc/mysql/mysql.conf.d/mysqld.cnf
        cat /etc/mysql/mysql.conf.d/mysqld.cnf
        sudo systemctl start mysql.service
        sudo systemctl status mysql.service
        echo "kaishi"
        cat /var/log/mysql/error.log
        echo "jieshu"
        curl 127.0.0.1:3306
        result=$(sudo mysql -u root -s -e "CREATE DATABASE IF NOT EXISTS test;" 2>&1)
        echo "$result"
#        TEMP_PASSWORD=$(grep "A temporary password" /var/log/mysqld.log | awk '{print $NF}')
#        echo "Temporary Password: $TEMP_PASSWORD"
#        sudo mysql_secure_installation << EOF
#        n
#        y
#        "$TEST_SECRET"
#        "$TEST_SECRET"
#        y
#        n
#        n
#        y
#        EOF
#        echo ""|sudo mysql -u root -p -e "CREATE DATABASE IF NOT EXISTS test;"
    - name: package demos
      shell: bash
      run: |
        mvn package -Dmariadb.version=${{ matrix.mysqlClientVersion }} -DskipTests -Pmysql-test --file \
        sermant-integration-tests/database-write-prohibition-test/pom.xml
    - name: start mysql demo
      shell: bash
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        -Dsermant_log_dir=${{ env.logDir }}/mysql \
        sermant-integration-tests/database-write-prohibition-test/mariadb-demo/target/mariadb-demo.jar > ${{ env.logDir }}/mariadb.log 2>&1 &
    - name: waiting for services start
      shell: bash
      run: |
        ps -ef | grep java
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:9098/static/checkStatus 120
    - name: test mysql
      shell: bash
      run: |
        mvn test -Ddatabase.write.prohibition.integration.test.type=MARIADB --file \
        sermant-integration-tests/database-write-prohibition-test/database-write-prohibition-integration-test/pom.xml
#    - name: Set up root password
#      shell: bash
#      run: |
#        TEMP_PASSWORD=$(sudo grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}')
#        mysql -u root -p"$TEMP_PASSWORD" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
#        mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
    - name: exit
      if: always()
      uses: ./.github/actions/common/exit
      with:
        processor-keyword: mariadb
    - name: if failure then upload error log
      uses: actions/upload-artifact@v3
      if: ${{ failure() || cancelled() }}
      with:
        name: (${{ github.job }})-database-write-prohibition-mariadb-(${{ matrix.mysqlClientVersion }}-logs
        path: |
          ./*.log
          ./logs/**
        if-no-files-found: warn
        retention-days: 2