# Spring Boot应用程序配置
spring:
  application:
    name: demo-consumer
  main:
    allow-bean-definition-overriding: true

# Dubbo配置
dubbo:
  application:
    name: demo-consumer
    qos-port: 33333
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: -1

# override common configurations in common module
servicecomb-config-order: 10

servicecomb:
  service:
    application: demo-test
    name: demo-consumer
    version: 1.2.0
    registry:
      # Default using local service center
      address: http://localhost:30100
      # address: https://cse.cn-south-1.myhuaweicloud.com
      instance:
        watch: false

  nacos:
    serverAddr: http://localhost:8848
    group: servicecomb
    dataId: servicecomb-1
    namespace: public
    contentType: properties
    addPrefix: false

  rest:
    address: 0.0.0.0:9041  # should be same with server.port to use web container