name: "Common operations"
description: "do something common for database-write-prohibition plugin test"
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ env.javaVersion }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.javaVersion }}
        distribution: 'adopt'
        cache: maven
    - name: get zookeeper from cache
      uses: actions/cache@v3
      with:
        path: apache-zookeeper-3.6.3-bin.tar.gz
        key: ${{ runner.os }}-apache-zookeeper-3.6.3
    - name: run zookeeper
      shell: bash
      run: |
        tar -zxf apache-zookeeper-3.6.3-bin.tar.gz
        bash apache-zookeeper-3.6.3-bin/bin/zkServer.sh start apache-zookeeper-3.6.3-bin/conf/zoo_sample.cfg
    - name: cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: cache agent
      uses: actions/cache@v3
      with:
        path: sermant-agent-*/
        key: ${{ runner.os }}-agent-${{ github.run_id }}
    - name: entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/database-write-prohibition/common
        key: ${{ runner.os }}-agent-${{ github.run_id }}