name: database-write-prohibition integration test
env:
  sermantVersion: 1.0.0
on:
  push:
  pull_request:
    branches:
      - '*'
    paths:
      - 'sermant-agentcore/**'
      - 'sermant-integration-tests/database-write-prohibition-test/**'
      - 'sermant-plugins/sermant-database-write-prohibition/**'
      - '.github/workflows/database_write_prohibition_integration_test.yml'
      - '.github/actions/common/database-write-prohibition/**'
      - '.github/actions/scenarios/database-write-prohibition/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  download-midwares-and-cache:
    name: download midwares and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache zookeeper
        uses: actions/cache@v3
        with:
          path: apache-zookeeper-3.6.3-bin.tar.gz
          key: ${{ runner.os }}-apache-zookeeper-3.6.3
          restore-keys: |
            ${{ runner.os }}-apache-zookeeper-3.6.3
      - name: download zookeeper
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh zk
#      - name: cache mongodb
#        uses: actions/cache@v3
#        with:
#          path: mongodb-linux-x86_64-ubuntu2004-7.0.6.tgz
#          key: ${{ runner.os }}-mongodb-linux-x86_64-ubuntu2004-7.0.6
#          restore-keys: |
#            ${{ runner.os }}-mongodb-linux-x86_64-ubuntu2004-7.0.6
#      - name: download mongodb
#        run: |
#          export ROOT_PATH=$(pwd)
#          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh mongodb
#      - name: cache mysql
#        uses: actions/cache@v3
#        with:
#          path: mysql-8.0.28-linux-glibc2.12-x86_64.tar.xz
#          key: ${{ runner.os }}-mysql-8.0.28-linux-glibc2.12-x86_64
#          restore-keys: |
#            ${{ runner.os }}-mysql-8.0.28-linux-glibc2.12-x86_64
#      - name: download mysql
#        run: |
#          export ROOT_PATH=$(pwd)
#          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh mysql
  build-agent-and-cache:
    name: build agent and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: cache agent
        uses: actions/cache@v3
        with:
          path: sermant-agent-*/
          key: ${{ runner.os }}-agent-${{ github.run_id }}
      - name: package agent
        run: |
          sed -i '/sermant-backend/d' pom.xml
          sed -i '/sermant-integration-tests/d' pom.xml
          sed -i '/sermant-injector/d' pom.xml
          mvn package -DskipTests -Ptest --file pom.xml
#  test-for-database-write-prohibition-mongodb:
#    name: Test for database-write-prohibition mongodb
#    runs-on: ubuntu-latest
#    needs: [build-agent-and-cache, download-midwares-and-cache]
#    strategy:
#      matrix:
#        include:
#          - mongodbClientVersion: "3.7.0"
#          - mongodbClientVersion: "3.9.1"
#          - mongodbClientVersion: "3.10.2"
#          - mongodbClientVersion: "3.11.3"
#          - mongodbClientVersion: "3.12.14"
#          - mongodbClientVersion: "4.0.6"
#          - mongodbClientVersion: "4.2.3"
#          - mongodbClientVersion: "4.5.1"
#          - mongodbClientVersion: "4.7.2"
#          - mongodbClientVersion: "4.9.1"
#          - mongodbClientVersion: "4.11.1"
#      fail-fast: false
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 100
#      - name: set java version to environment
#        run: |
#          echo "javaVersion=8" >> $GITHUB_ENV
#      - name: common operations
#        uses: ./.github/actions/common/database-write-prohibition
#      - name: database-write-prohibition-mongodb test for mongodbClientVersion=${{ matrix.mongodbClientVersion }}
#        uses: ./.github/actions/scenarios/database-write-prohibition/mongodb
  test-for-database-write-prohibition-mysql:
    name: Test for database-write-prohibition mysql
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache, download-midwares-and-cache]
    strategy:
      matrix:
        include:
          - mysqlClientVersion: "2.6.2"
#          - mysqlClientVersion: "2.7.6"
#          - mysqlClientVersion: "2.7.12"
#          - mysqlClientVersion: "3.0.6"
#          - mysqlClientVersion: "3.0.11"
#          - mysqlClientVersion: "3.1.4"
#          - mysqlClientVersion: "3.2.0"
#          - mysqlClientVersion: "3.3.3"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: common operations
        uses: ./.github/actions/common/database-write-prohibition
      - name: database-write-prohibition-mysql test for mysqlVersion=${{ matrix.mysqlVersion }}
        uses: ./.github/actions/scenarios/database-write-prohibition/mysql