name: Tagtransmission integration test
env:
  projectSpringBootVersion: 2.7.15
  sermantVersion: 1.0.0
on:
  push:
  pull_request:
    branches:
      - '*'
    paths:
      - 'sermant-agentcore/**'
      - 'sermant-integration-tests/**'
      - 'sermant-plugins/sermant-tag-transmission/**'
      - '.github/workflows/tagtransmission_integration_test.yml'
      - '.github/actions/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  download-midwares-and-cache:
    name: download midwares and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache local cse
        uses: actions/cache@v3
        with:
          path: Local-CSE-2.1.3-linux-amd64.zip
          key: ${{ runner.os }}-local-cse
          restore-keys: |
            ${{ runner.os }}-local-cse
      - name: download cse
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh cse
      - name: cache zookeeper
        uses: actions/cache@v3
        with:
          path: apache-zookeeper-3.6.3-bin.tar.gz
          key: ${{ runner.os }}-apache-zookeeper-3.6.3
          restore-keys: |
            ${{ runner.os }}-apache-zookeeper-3.6.3
      - name: download zookeeper
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh zk
      - name: cache nacos server
        uses: actions/cache@v3
        with:
          path: nacos-server-1.4.2.tar.gz
          key: ${{ runner.os }}-nacos-server-1.4.2
          restore-keys: |
            ${{ runner.os }}-nacos-server-1.4.2
      - name: download nacos
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh nacos
      - name: cache rocketmq
        uses: actions/cache@v3
        with:
          path: rocketmq-all-4.8.0-source-release.zip
          key: ${{ runner.os }}-rocketmq-all-4.8.0-source-release
          restore-keys: |
            ${{ runner.os }}-rocketmq-all-4.8.0-source-release
      - name: download rocketmq
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh rocketmq
      - name: cache kafka
        uses: actions/cache@v3
        with:
          path: kafka_2.13-2.7.0.tgz
          key: ${{ runner.os }}-kafka_2.13-2.7.0
          restore-keys: |
            ${{ runner.os }}-kafka_2.13-2.7.0
      - name: download kafka
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh kafka
  build-agent-and-cache:
    name: build agent and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: cache agent
        uses: actions/cache@v3
        with:
          path: sermant-agent-*/
          key: ${{ runner.os }}-agent-${{ github.run_id }}
      - name: package agent
        run: |
          sed -i '/sermant-backend/d' pom.xml
          sed -i '/sermant-backend-lite/d' pom.xml
          sed -i '/sermant-integration-tests/d' pom.xml
          sed -i '/sermant-injector/d' pom.xml
          sed -i '/sermant-flowcontrol/d' sermant-plugins/pom.xml
          mvn package -DskipTests -Ptest --file pom.xml
#  test-for-tag-transmission-httpclientv3:
#    name: Test for tag transmission httpclientv3
#    runs-on: ubuntu-latest
#    needs: [build-agent-and-cache, download-midwares-and-cache]
#    strategy:
#      matrix:
#        include:
#          - httpClientVersion: "3.0.1"
#          - httpClientVersion: "3.1"
#      fail-fast: false
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 100
#      - name: set java version to environment
#        run: |
#          echo "javaVersion=8" >> $GITHUB_ENV
#      - name: common operations
#        uses: ./.github/actions/common/tag-transmission
#      - name: tag transmission test for httpClientVersion=${{ matrix.httpClientVersion }}
#        if: env.enableTagTransmission == 'true'
#        uses: ./.github/actions/scenarios/tag-transmission/httpclientv3
#  test-for-tag-transmission-httpclientv4:
#    name: Test for tag transmission httpclientv4
#    runs-on: ubuntu-latest
#    needs: [build-agent-and-cache, download-midwares-and-cache]
#    strategy:
#      matrix:
#        include:
#          - httpClientVersion: "4.3.6"
#          - httpClientVersion: "4.4.1"
#          - httpClientVersion: "4.5.14"
#      fail-fast: false
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 100
#      - name: set java version to environment
#        run: |
#          echo "javaVersion=8" >> $GITHUB_ENV
#      - name: common operations
#        uses: ./.github/actions/common/tag-transmission
#      - name: tag transmission test for httpClientVersion=${{ matrix.httpClientVersion }}
#        if: env.enableTagTransmission == 'true'
#        uses: ./.github/actions/scenarios/tag-transmission/httpclientv4
#  test-for-tag-transmission-okhttp:
#    name: Test for tag transmission okhttp
#    runs-on: ubuntu-latest
#    needs: [build-agent-and-cache, download-midwares-and-cache]
#    strategy:
#      matrix:
#        include:
#          - okHttpVersion: "2.0.0"
#          - okHttpVersion: "2.1.0"
#          - okHttpVersion: "2.2.0"
#          - okHttpVersion: "2.3.0"
#          - okHttpVersion: "2.4.0"
#          - okHttpVersion: "2.5.0"
#          - okHttpVersion: "2.6.0"
#          - okHttpVersion: "2.7.5"
#      fail-fast: false
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 100
#      - name: set java version to environment
#        run: |
#          echo "javaVersion=8" >> $GITHUB_ENV
#      - name: common operations
#        uses: ./.github/actions/common/tag-transmission
#      - name: tag transmission test for okHttpVersion=${{ matrix.okHttpVersion }}
#        if: env.enableTagTransmission == 'true'
#        uses: ./.github/actions/scenarios/tag-transmission/okhttp
#  test-for-tag-transmission-grpc:
#    name: Test for tag transmission grpc
#    runs-on: ubuntu-latest
#    needs: [build-agent-and-cache, download-midwares-and-cache]
#    strategy:
#      matrix:
#        include:
#          - grpcVersion: "1.13.1"
#          - grpcVersion: "1.21.0"
#          - grpcVersion: "1.31.0"
#          - grpcVersion: "1.41.0"
#          - grpcVersion: "1.52.1"
#          - grpcVersion: "1.58.0"
#      fail-fast: false
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 100
#      - name: set java version to environment
#        run: |
#          echo "javaVersion=8" >> $GITHUB_ENV
#      - name: common operations
#        uses: ./.github/actions/common/tag-transmission
#      - name: tag transmission test for grpcVersion=${{ matrix.grpcVersion }}
#        if: env.enableTagTransmission == 'true'
#        uses: ./.github/actions/scenarios/tag-transmission/grpc
  test-for-tag-transmission-sofarpc:
    name: Test for tag transmission grpc
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache, download-midwares-and-cache]
    strategy:
      matrix:
        include:
          - sofaRpcVersion: "5.3.4"
          - sofaRpcVersion: "5.4.8"
          - sofaRpcVersion: "5.5.9"
          - sofaRpcVersion: "5.6.5"
          - sofaRpcVersion: "5.7.10"
          - sofaRpcVersion: "5.8.8"
          - sofaRpcVersion: "5.9.2"
          - sofaRpcVersion: "5.10.0"
          - sofaRpcVersion: "5.11.1"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: common operations
        uses: ./.github/actions/common/tag-transmission
      - name: tag transmission test for sofaRpcVersion=${{ matrix.sofaRpcVersion }}
        if: env.enableTagTransmission == 'true'
        uses: ./.github/actions/scenarios/tag-transmission/sofarpc
  test-for-tag-transmission-servicecomb:
    name: Test for tag transmission servicecomb
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache, download-midwares-and-cache]
    strategy:
      matrix:
        include:
          - serviceCombVersion: "2.0.2"
          - serviceCombVersion: "2.1.6"
          - serviceCombVersion: "2.2.4"
          - serviceCombVersion: "2.3.6"
          - serviceCombVersion: "2.5.3"
          - serviceCombVersion: "2.6.3"
          - serviceCombVersion: "2.7.10"
          - serviceCombVersion: "2.8.12"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: common operations
        uses: ./.github/actions/common/tag-transmission
      - name: tag transmission test for servicecombVersion=${{ matrix.serviceCombVersion }}
        if: env.enableTagTransmission == 'true'
        uses: ./.github/actions/scenarios/tag-transmission/servicecomb
  test-for-tag-transmission-alibabadubbo:
    name: Test for tag transmission alibabadubbo
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache, download-midwares-and-cache]
    strategy:
      matrix:
        include:
          - alibabaDubboVersion: "2.6.0"
          - alibabaDubboVersion: "2.6.3"
          - alibabaDubboVersion: "2.6.6"
          - alibabaDubboVersion: "2.6.9"
          - alibabaDubboVersion: "2.6.12"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: common operations
        uses: ./.github/actions/common/tag-transmission
      - name: tag transmission test for alibabaDubboVersion=${{ matrix.alibabaDubboVersion }}
        if: env.enableTagTransmission == 'true'
        uses: ./.github/actions/scenarios/tag-transmission/alibaba-dubbo
  test-for-tag-transmission-apachedubbo:
    name: Test for tag transmission grpc
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache, download-midwares-and-cache]
    strategy:
      matrix:
        include:
          - apacheDubboVersion: "2.7.0"
          - apacheDubboVersion: "2.7.15"
          - apacheDubboVersion: "2.7.23"
          - apacheDubboVersion: "3.0.15"
          - apacheDubboVersion: "3.1.11"
          - apacheDubboVersion: "3.2.7"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: common operations
        uses: ./.github/actions/common/tag-transmission
      - name: tag transmission test for apacheDubboVersion=${{ matrix.apacheDubboVersion}}
        if: env.enableTagTransmission == 'true'
        uses: ./.github/actions/scenarios/tag-transmission/apache-dubbo
  test-for-tag-transmission-crossthread:
    name: Test for tag transmission crossthread
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache, download-midwares-and-cache]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: common operations
        uses: ./.github/actions/common/tag-transmission
      - name: tag transmission test for crossthread
        if: env.enableTagTransmission == 'true'
        uses: ./.github/actions/scenarios/tag-transmission/crossthread
  test-for-tag-transmission-config:
    name: Test for tag transmission config
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache, download-midwares-and-cache]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: common operations
        uses: ./.github/actions/common/tag-transmission
      - name: tag transmission test for config
        if: env.enableTagTransmission == 'true'
        uses: ./.github/actions/scenarios/tag-transmission/config